export type Campus = {
  name: string;
  city?: string;
  state: string;
  region: Region;
};

export type Region =
  | "Illinois"
  | "Ivy League"
  | "California"
  | "New York"
  | "Texas"
  | "Florida"
  | "Pennsylvania"
  | "Massachusetts"
  | "Other";

export const REGIONS: Region[] = [
  "Illinois",
  "Ivy League",
  "California",
  "New York",
  "Texas",
  "Florida",
  "Pennsylvania",
  "Massachusetts",
  "Other",
];

export const CAMPUSES: Campus[] = [
  // Illinois
  { name: "DePaul University — Lincoln Park", city: "Chicago", state: "IL", region: "Illinois" },
  { name: "DePaul University — Loop", city: "Chicago", state: "IL", region: "Illinois" },
  { name: "Northwestern University", city: "Evanston", state: "IL", region: "Illinois" },
  { name: "University of Chicago", city: "Chicago", state: "IL", region: "Illinois" },
  { name: "University of Illinois Chicago", city: "Chicago", state: "IL", region: "Illinois" },
  { name: "Loyola University Chicago", city: "Chicago", state: "IL", region: "Illinois" },
  { name: "Illinois Institute of Technology", city: "Chicago", state: "IL", region: "Illinois" },
  { name: "Columbia College Chicago", city: "Chicago", state: "IL", region: "Illinois" },
  { name: "University of Illinois Urbana-Champaign", city: "Urbana", state: "IL", region: "Illinois" },
  { name: "Northern Illinois University", city: "DeKalb", state: "IL", region: "Illinois" },
  { name: "Illinois State University", city: "Normal", state: "IL", region: "Illinois" },
  { name: "Southern Illinois University Carbondale", city: "Carbondale", state: "IL", region: "Illinois" },
  { name: "Bradley University", city: "Peoria", state: "IL", region: "Illinois" },
  { name: "Eastern Illinois University", city: "Charleston", state: "IL", region: "Illinois" },
  { name: "Western Illinois University", city: "Macomb", state: "IL", region: "Illinois" },

  // Ivy League
  { name: "Harvard University", city: "Cambridge", state: "MA", region: "Ivy League" },
  { name: "Yale University", city: "New Haven", state: "CT", region: "Ivy League" },
  { name: "Princeton University", city: "Princeton", state: "NJ", region: "Ivy League" },
  { name: "Columbia University", city: "New York", state: "NY", region: "Ivy League" },
  { name: "University of Pennsylvania", city: "Philadelphia", state: "PA", region: "Ivy League" },
  { name: "Brown University", city: "Providence", state: "RI", region: "Ivy League" },
  { name: "Dartmouth College", city: "Hanover", state: "NH", region: "Ivy League" },
  { name: "Cornell University", city: "Ithaca", state: "NY", region: "Ivy League" },

  // California
  { name: "Stanford University", state: "CA", region: "California" },
  { name: "UCLA", state: "CA", region: "California" },
  { name: "USC", state: "CA", region: "California" },
  { name: "UC Berkeley", state: "CA", region: "California" },
  { name: "Caltech", state: "CA", region: "California" },
  { name: "UC San Diego", state: "CA", region: "California" },
  { name: "UC Irvine", state: "CA", region: "California" },
  { name: "UC Davis", state: "CA", region: "California" },
  { name: "UC Santa Barbara", state: "CA", region: "California" },
  { name: "UC Santa Cruz", state: "CA", region: "California" },
  { name: "UC Riverside", state: "CA", region: "California" },
  { name: "San Diego State University", state: "CA", region: "California" },
  { name: "San Jose State University", state: "CA", region: "California" },
  { name: "SF State", state: "CA", region: "California" },
  { name: "University of San Francisco", state: "CA", region: "California" },
  { name: "Santa Clara University", state: "CA", region: "California" },
  { name: "Pepperdine University", state: "CA", region: "California" },
  { name: "Loyola Marymount", state: "CA", region: "California" },
  { name: "Cal Poly SLO", state: "CA", region: "California" },
  { name: "Cal Poly Pomona", state: "CA", region: "California" },
  { name: "CSU Fresno", state: "CA", region: "California" },
  { name: "CSU Long Beach", state: "CA", region: "California" },
  { name: "CSU Fullerton", state: "CA", region: "California" },
  { name: "CSU Los Angeles", state: "CA", region: "California" },
  { name: "CSU Northridge", state: "CA", region: "California" },

  // New York
  { name: "NYU", state: "NY", region: "New York" },
  { name: "Fordham University", state: "NY", region: "New York" },
  { name: "Syracuse University", state: "NY", region: "New York" },
  { name: "University of Rochester", state: "NY", region: "New York" },
  { name: "University at Buffalo", state: "NY", region: "New York" },
  { name: "Stony Brook University", state: "NY", region: "New York" },
  { name: "Binghamton University", state: "NY", region: "New York" },
  { name: "University at Albany", state: "NY", region: "New York" },
  { name: "RPI", state: "NY", region: "New York" },
  { name: "Colgate University", state: "NY", region: "New York" },
  { name: "Hamilton College", state: "NY", region: "New York" },
  { name: "Vassar College", state: "NY", region: "New York" },
  { name: "Skidmore College", state: "NY", region: "New York" },
  { name: "Marist College", state: "NY", region: "New York" },
  { name: "Hofstra University", state: "NY", region: "New York" },
  { name: "Adelphi University", state: "NY", region: "New York" },
  { name: "St. John's University", state: "NY", region: "New York" },
  { name: "Pace University", state: "NY", region: "New York" },
  { name: "LIU", state: "NY", region: "New York" },
  { name: "Baruch College", state: "NY", region: "New York" },
  { name: "Hunter College", state: "NY", region: "New York" },
  { name: "CCNY", state: "NY", region: "New York" },
  { name: "Brooklyn College", state: "NY", region: "New York" },
  { name: "Queens College", state: "NY", region: "New York" },
  { name: "SUNY (10 additional campuses)", state: "NY", region: "New York" },

  // Texas
  { name: "UT Austin", state: "TX", region: "Texas" },
  { name: "Texas A&M", state: "TX", region: "Texas" },
  { name: "SMU", state: "TX", region: "Texas" },
  { name: "Baylor University", state: "TX", region: "Texas" },
  { name: "TCU", state: "TX", region: "Texas" },
  { name: "Rice University", state: "TX", region: "Texas" },
  { name: "Texas Tech", state: "TX", region: "Texas" },
  { name: "University of Houston", state: "TX", region: "Texas" },
  { name: "UNT", state: "TX", region: "Texas" },
  { name: "UT Dallas", state: "TX", region: "Texas" },
  { name: "UT Arlington", state: "TX", region: "Texas" },
  { name: "UT San Antonio", state: "TX", region: "Texas" },
  { name: "UT El Paso", state: "TX", region: "Texas" },
  { name: "Texas State", state: "TX", region: "Texas" },
  { name: "Sam Houston State", state: "TX", region: "Texas" },
  { name: "SFA", state: "TX", region: "Texas" },
  { name: "UTRGV", state: "TX", region: "Texas" },
  { name: "Lamar University", state: "TX", region: "Texas" },
  { name: "Trinity University", state: "TX", region: "Texas" },
  { name: "St. Mary's University", state: "TX", region: "Texas" },
  { name: "Abilene Christian", state: "TX", region: "Texas" },

  // Florida
  { name: "University of Florida", state: "FL", region: "Florida" },
  { name: "Florida State University", state: "FL", region: "Florida" },
  { name: "UCF", state: "FL", region: "Florida" },
  { name: "USF", state: "FL", region: "Florida" },
  { name: "FIU", state: "FL", region: "Florida" },
  { name: "FAU", state: "FL", region: "Florida" },
  { name: "UNF", state: "FL", region: "Florida" },
  { name: "University of Miami", state: "FL", region: "Florida" },
  { name: "Rollins College", state: "FL", region: "Florida" },
  { name: "Stetson University", state: "FL", region: "Florida" },

  // Pennsylvania
  { name: "Penn State", state: "PA", region: "Pennsylvania" },
  { name: "University of Pittsburgh", state: "PA", region: "Pennsylvania" },
  { name: "Carnegie Mellon", state: "PA", region: "Pennsylvania" },
  { name: "Temple University", state: "PA", region: "Pennsylvania" },
  { name: "Drexel University", state: "PA", region: "Pennsylvania" },
  { name: "Villanova University", state: "PA", region: "Pennsylvania" },
  { name: "Lehigh University", state: "PA", region: "Pennsylvania" },
  { name: "Bucknell University", state: "PA", region: "Pennsylvania" },
  { name: "Lafayette College", state: "PA", region: "Pennsylvania" },
  { name: "Gettysburg College", state: "PA", region: "Pennsylvania" },
  { name: "Dickinson College", state: "PA", region: "Pennsylvania" },
  { name: "Muhlenberg College", state: "PA", region: "Pennsylvania" },

  // Massachusetts
  { name: "MIT", state: "MA", region: "Massachusetts" },
  { name: "Tufts University", state: "MA", region: "Massachusetts" },
  { name: "Boston College", state: "MA", region: "Massachusetts" },
  { name: "Boston University", state: "MA", region: "Massachusetts" },
  { name: "Northeastern University", state: "MA", region: "Massachusetts" },
  { name: "UMass Amherst", state: "MA", region: "Massachusetts" },
  { name: "Williams College", state: "MA", region: "Massachusetts" },
  { name: "Amherst College", state: "MA", region: "Massachusetts" },
  { name: "Wellesley College", state: "MA", region: "Massachusetts" },
  { name: "Smith College", state: "MA", region: "Massachusetts" },
  { name: "Mount Holyoke", state: "MA", region: "Massachusetts" },
  { name: "Holy Cross", state: "MA", region: "Massachusetts" },
  { name: "WPI", state: "MA", region: "Massachusetts" },
  { name: "Brandeis University", state: "MA", region: "Massachusetts" },
  { name: "Babson College", state: "MA", region: "Massachusetts" },
  { name: "Bentley University", state: "MA", region: "Massachusetts" },
  { name: "Suffolk University", state: "MA", region: "Massachusetts" },
  { name: "Emerson College", state: "MA", region: "Massachusetts" },
  { name: "Simmons University", state: "MA", region: "Massachusetts" },

  // Other notable regions
  { name: "University of Georgia", state: "GA", region: "Other" },
  { name: "Georgia Tech", state: "GA", region: "Other" },
  { name: "Emory University", state: "GA", region: "Other" },
  { name: "Duke University", state: "NC", region: "Other" },
  { name: "UNC Chapel Hill", state: "NC", region: "Other" },
  { name: "NC State", state: "NC", region: "Other" },
  { name: "Wake Forest", state: "NC", region: "Other" },
  { name: "University of Virginia", state: "VA", region: "Other" },
  { name: "Virginia Tech", state: "VA", region: "Other" },
  { name: "William & Mary", state: "VA", region: "Other" },
  { name: "Vanderbilt", state: "TN", region: "Other" },
  { name: "University of Tennessee", state: "TN", region: "Other" },
  { name: "Ohio State", state: "OH", region: "Other" },
  { name: "Case Western Reserve", state: "OH", region: "Other" },
  { name: "Ohio University", state: "OH", region: "Other" },
  { name: "Miami University", state: "OH", region: "Other" },
  { name: "University of Michigan", state: "MI", region: "Other" },
  { name: "Michigan State", state: "MI", region: "Other" },
  { name: "UW-Madison", state: "WI", region: "Other" },
  { name: "Marquette University", state: "WI", region: "Other" },
  { name: "University of Washington", state: "WA", region: "Other" },
  { name: "Washington State", state: "WA", region: "Other" },
  { name: "Georgetown", state: "DC", region: "Other" },
  { name: "George Washington", state: "DC", region: "Other" },
  { name: "American University", state: "DC", region: "Other" },
  { name: "Howard University", state: "DC", region: "Other" },
  { name: "Johns Hopkins", state: "MD", region: "Other" },
  { name: "University of Maryland", state: "MD", region: "Other" },
  { name: "Rutgers", state: "NJ", region: "Other" },
  { name: "Indiana University", state: "IN", region: "Other" },
  { name: "Purdue University", state: "IN", region: "Other" },
  { name: "Notre Dame", state: "IN", region: "Other" },
  { name: "University of Minnesota", state: "MN", region: "Other" },
  { name: "University of Iowa", state: "IA", region: "Other" },
  { name: "Iowa State", state: "IA", region: "Other" },
  { name: "University of Missouri", state: "MO", region: "Other" },
  { name: "Wash U in St. Louis", state: "MO", region: "Other" },
  { name: "University of Kansas", state: "KS", region: "Other" },
  { name: "Kansas State", state: "KS", region: "Other" },
  { name: "University of Nebraska", state: "NE", region: "Other" },
  { name: "University of Oklahoma", state: "OK", region: "Other" },
  { name: "Oklahoma State", state: "OK", region: "Other" },
  { name: "University of Arkansas", state: "AR", region: "Other" },
  { name: "LSU", state: "LA", region: "Other" },
  { name: "Tulane", state: "LA", region: "Other" },
  { name: "Ole Miss", state: "MS", region: "Other" },
  { name: "Mississippi State", state: "MS", region: "Other" },
  { name: "University of Alabama", state: "AL", region: "Other" },
  { name: "Auburn University", state: "AL", region: "Other" },
  { name: "University of Kentucky", state: "KY", region: "Other" },
  { name: "University of Louisville", state: "KY", region: "Other" },
  { name: "University of South Carolina", state: "SC", region: "Other" },
  { name: "Clemson University", state: "SC", region: "Other" },
  { name: "West Virginia University", state: "WV", region: "Other" },
  { name: "University of Colorado Boulder", state: "CO", region: "Other" },
  { name: "Colorado State", state: "CO", region: "Other" },
  { name: "University of Utah", state: "UT", region: "Other" },
  { name: "BYU", state: "UT", region: "Other" },
  { name: "University of Arizona", state: "AZ", region: "Other" },
  { name: "Arizona State", state: "AZ", region: "Other" },
  { name: "University of New Mexico", state: "NM", region: "Other" },
  { name: "University of Nevada, Las Vegas", state: "NV", region: "Other" },
  { name: "University of Nevada, Reno", state: "NV", region: "Other" },
  { name: "University of Oregon", state: "OR", region: "Other" },
  { name: "Oregon State", state: "OR", region: "Other" },
  { name: "University of Hawaii", state: "HI", region: "Other" },
  { name: "University of Alaska Anchorage", state: "AK", region: "Other" },
  { name: "University of Montana", state: "MT", region: "Other" },
  { name: "University of Idaho", state: "ID", region: "Other" },
  { name: "University of Wyoming", state: "WY", region: "Other" },
  { name: "University of North Dakota", state: "ND", region: "Other" },
  { name: "University of South Dakota", state: "SD", region: "Other" },
  { name: "University of Vermont", state: "VT", region: "Other" },
  { name: "University of Maine", state: "ME", region: "Other" },
  { name: "University of New Hampshire", state: "NH", region: "Other" },
  { name: "University of Connecticut", state: "CT", region: "Other" },
  { name: "University of Rhode Island", state: "RI", region: "Other" },
  { name: "University of Delaware", state: "DE", region: "Other" },
];

export const TOTAL_CAMPUSES = 306;
export const TOTAL_INSTITUTIONS = 305;
export const TOTAL_STATES = 46;
